run:
  timeout: 10m
  skip-dirs:
    - gen

linters:
  enable-all: true
  disable:
    - dupl # allow duplication
    - funlen # allow long functions
    - gomnd # allow some magic numbers
    - wsl # unwanted amount of whitespace
    - godox # allow TODOs
    - interfacer # deprecated by the author for having too many false positives
    - gocognit # allow higher cognitive complexity
    - testpackage # unwanted convention
    - nestif # allow deep nesting
    - unparam # allow constant parameters
    - goerr113 # allow "dynamic" errors
    - nlreturn # don't enforce newline before return
    - paralleltest # TODO: fix issues and enable
    - exhaustivestruct # don't require exhaustive struct fields
    - wrapcheck # don't require wrapping everywhere
    - gochecknoglobals # don't enforce
    - gosec # TODO: fix issues and enable
    - cyclop # don't enforce
    - forbidigo # don't enforce
    - noctx # TODO: migrate to context-based HTTP APIs
    - scopelint # deprecated upstream, replaced by exportloopref
    - golint # deprecated upstream, replaced by revive
    - maligned # deprecated, replaced by govet
    - revive # we are stuttering a lot
