name: Setup Sage
description: Setup Sage, including caching of tools and Go modules.

inputs:
  cacheKey:
    description: Custom cache key used
    required: false
    default: ${{ github.workflow }}.${{ github.job }}

  go-version:
    description: The Go version to download (if necessary) and use. Supports semver spec and ranges.
    required: false
    default: ^1.17

  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    default: 0

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Needed for conventional commit linting.
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: ${{ inputs.go-version }}

    - name: Cache Go modules
      uses: actions/cache@v2
      with:
        path: |
          ~/.cache/go-build
          ~/go/pkg/mod
        key: ${{ runner.os }}-go-${{ inputs.cacheKey }}-${{ hashFiles('**/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-go-${{ inputs.cacheKey }}-

    - name: Cache sage folders
      uses: actions/cache@v2
      with:
        path: |
          ./.sage/tools
          ./.sage/bin
        key: ${{ runner.os }}-sage-${{ inputs.cacheKey }}-${{ hashFiles('./.sage/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-sage-${{ inputs.cacheKey }}-
