name: Setup Sage
description: Setup Sage, including caching of tools and Go modules.

inputs:
  cacheKey:
    description: Custom cache key used
    required: false
    default: cachekey

  disableCache:
    description: Disable cache
    required: false
    default: false

  go-version:
    description: The Go version to download (if necessary) and use. Supports semver spec and ranges.
    required: false
    default: '1.21'

  check-latest:
    description: If true, checks whether the cached go version is the latest, if not then downloads the latest. Useful when you need to use the latest version.
    required: false
    default: false

  fetch-depth:
    description: Number of commits to fetch. 0 indicates all history for all branches and tags.
    default: 0

runs:
  using: composite

  steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        # Needed for conventional commit linting.
        fetch-depth: ${{ inputs.fetch-depth }}

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ inputs.go-version }}
        check-latest: ${{ inputs.check-latest }}
        cache: ${{ inputs.disableCache != 'true' }}

    - name: Cache sage folders
      if: ${{ inputs.disableCache != 'true' }}
      uses: actions/cache@v3
      with:
        path: |
          ./.sage/tools
          ./.sage/bin
        key: ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ inputs.go-version }}-${{ hashFiles('./.sage/go.sum') }}
        restore-keys: |
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-${{ inputs.go-version }}-
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-${{ inputs.cacheKey }}-
          ${{ runner.os }}-sage-${{ github.workflow }}-${{ github.job }}-
          ${{ runner.os }}-sage-${{ github.workflow }}-
          ${{ runner.os }}-sage-
