name: Go

on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.4.0
        with:
          fetch-depth: 0

      - name: Setup Go toolchain
        uses: ./actions/setup-go
        with:
          cacheKey: build

      - name: Make
        run: make
