name: Release

on:
  push:
    branches: [ main ]

permissions: write-all

jobs:

  release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.17

    - name: Set up Node
      uses: actions/setup-node@v2
      with:
        node-version: ^14

    - name: Configure git for private modules
      env:
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: git config --global url."https://git:${TOKEN}@github.com/einride/".insteadOf "https://github.com/einride/"

    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: make semantic-release-run branch=main ci=true
