name: Release

on:
  push:
    branches: [master]

permissions: write-all

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.0

      - name: Setup Sage
        uses: ./actions/setup

      - name: Make
        run: make

      - name: Release
        uses: go-semantic-release/action@v1.15.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          allow-initial-development-versions: true
